name: Set up Nix

description: Set up Nix with binary cache enabled

inputs:
  cachix-name:
    description: Name of the Cachix account
    required: false
    default: akirak
  cachix-token:
    description: Auth token for cachix
    required: true

runs:
  using: composite
  steps:
    - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Restore the package cache
      uses: nix-community/cache-nix-action@106bba72ed8e29c8357661199511ef07790175e9 # v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
        # Optionally, you can add extra paths saved to the cache.
        #
        # paths: |
        #   node_modules/.pnpm

    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: ${{ inputs.cachix-name }}
        authToken: '${{ inputs.cachix-token }}'
